version: '3.5'
services:

  mkdocs:
    image: "${TRAEFIK_IMAGE}"
    build:
      context: .
      dockerfile: Dockerfile-centos    

  mkdocs-alpine:
    image: "${TRAEFIK_ALPINE_IMAGE}"
    build:
      context: .
      dockerfile: Dockerfile-alpine