version: '3.5'
services:

  traefik-centos:
    image: "${TRAEFIK_IMAGE}"
    build:
      context: .
      dockerfile: Dockerfile-centos    

  traefik-alpine:
    image: "${TRAEFIK_ALPINE_IMAGE}"
    build:
      context: .
      dockerfile: Dockerfile-alpine
